version: "3.9"

services:
  portfolio:
    build: . # Build the image from the current directory
    image: my_portfolio_image # Name your image for easier reference
    container_name: my_portfolio
    ports:
      - "80:80"
  # Removed the copy section

volumes:
  website: # Define the volume name (not used in this approach)

