services:
  portfolio:
    build:
      context: . # Context should be the root of the project
      dockerfile: html/Dockerfile # Pointing to the Dockerfile inside the 'website' directory
    container_name: my_portfolio_Engl
    ports:
      - "3004:80"
    restart: always
