version: "3.9"

services:
  portfolio:
    build:
      context: . # Context should be the root of the project
      dockerfile: website/Dockerfile # Pointing to the Dockerfile inside the 'website' directory
    container_name: my_portfolio
    ports:
      - "3000:80"
    restart: always
