version: "3.9"

services:
  portfolio:
    image: nginx:latest
    container_name: my_portfolio
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html/:ro
    restart: unless-stopped
