version: "3.9"

services:
  portfolio:
    image: nginx:latest
    container_name: my_portfolio
    ports:
      - "80:80"
    volumes:
      - /home/user1/Docker/portfolio/website:/usr/share/nginx/html/
    restart: always

volumes:
  website:
