services:
  portfolio:
    image: nginx:latest
    container_name: my_portfolio
    ports:
      - "3000:80"
      - "3001:443"
    volumes:
      - ./website:/usr/share/nginx/html
    restart: always
# No need to define volumes under the volumes key, as you're directly binding a local folder

