services:
  portfolio:
    build: . # This tells Docker Compose to build the image from the Dockerfile in the current directory
    container_name: my_portfolio
    ports:
      - "3000:80"
    restart: always
